##0. Pytorch fundamentals

In [ ]:
import torch
torch.__version__

'2.0.1+cu118'

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Introduction to tensors

In [ ]:
### Creating tensors

In [ ]:
scalar = torch.tensor([7, 8, 9])
scalar

tensor([7, 8, 9])

Pytorch tensors are created using torch.Tensor()

In [ ]:
scalar.ndim

1

In [ ]:
vector = torch.tensor([1,7])
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])

MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9040, 0.5017, 0.3536, 0.3028],
        [0.4468, 0.9388, 0.1340, 0.9206],
        [0.6978, 0.6067, 0.4289, 0.4729]])

In [ ]:
#Create a random tensor with similiar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3, 224, 224)) #height, width and color channels
random_image_size_tensor

tensor([[[0.6171, 0.0208, 0.3650,  ..., 0.5131, 0.1760, 0.9980],
         [0.1740, 0.4004, 0.3702,  ..., 0.9883, 0.6039, 0.7851],
         [0.7830, 0.6194, 0.6808,  ..., 0.5516, 0.5894, 0.6647],
         ...,
         [0.6970, 0.1122, 0.4817,  ..., 0.6345, 0.5964, 0.8342],
         [0.7561, 0.6296, 0.6595,  ..., 0.6211, 0.9680, 0.2172],
         [0.1660, 0.0373, 0.8578,  ..., 0.0862, 0.3343, 0.6324]],

        [[0.6777, 0.8314, 0.3404,  ..., 0.8045, 0.4798, 0.3402],
         [0.5119, 0.5017, 0.4596,  ..., 0.3381, 0.4661, 0.0600],
         [0.9801, 0.4549, 0.6807,  ..., 0.5468, 0.5546, 0.8419],
         ...,
         [0.7510, 0.7342, 0.0898,  ..., 0.0405, 0.0835, 0.3427],
         [0.2343, 0.6353, 0.1725,  ..., 0.8483, 0.5297, 0.6260],
         [0.9668, 0.2396, 0.6874,  ..., 0.2009, 0.4255, 0.5637]],

        [[0.8674, 0.4715, 0.0692,  ..., 0.4814, 0.7186, 0.3493],
         [0.5781, 0.3527, 0.1988,  ..., 0.2711, 0.2715, 0.3441],
         [0.5463, 0.2767, 0.5386,  ..., 0.7660, 0.8668, 0.

In [ ]:
random_image_size_tensor.ndim

3

In [ ]:
torch.rand(size=(3,3))

tensor([[0.3832, 0.0807, 0.6977],
        [0.3806, 0.4229, 0.2805],
        [0.6023, 0.5947, 0.9774]])

In [ ]:
#Create a tensor of all zeros
zero = torch.zeros(size=(224, 224))
zero

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(224, 224))
ones.dtype

torch.float32

In [ ]:
random_image_size_tensor.dtype

torch.float32

### Create a range of tensors and tensors-like

In [ ]:
# Use torch.range()
torch.range(0, 10)

<ipython-input-22-74fde6f68c60>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0, 10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
one_to_hundred = torch.arange(start=0, end=100, step=10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Creating tensors like
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
hundred_zeros = torch.zeros_like(one_to_hundred)
hundred_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
hundred_ones = torch.ones_like(one_to_hundred)
hundred_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Tensor datatypes

#### **Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:


1. Tensors not right datatype.
2. Tensors not right shape.
3. Tensors not on the right device.

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What datatype is the tensor? float32 or float64, 16-bit, 32-bit complex etc
                               device=None, #What device is your tensor on?
                               requires_grad=False) #Whether or not to track gradients with the tensor operations.
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [ ]:
float_64_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float64)
float_64_tensor.dtype

torch.float64

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_test_tensor = float_16_tensor * float_32_tensor
float_test_tensor.dtype

torch.float32

In [ ]:
int32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

### Getting information from tensors

1. Tensors not right datatype - to get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not the right shape - to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the right device - can use tensor.device

In [ ]:
int32_tensor.device

device(type='cpu')

In [ ]:
#Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.4498, 0.2620, 0.7493, 0.4155],
        [0.1777, 0.8785, 0.2950, 0.2312],
        [0.3300, 0.9604, 0.3378, 0.7035]])

In [ ]:
print(some_tensor)
print(f"\n\nDataype of tensor: {some_tensor.dtype}\nShape of tensor: {some_tensor.size()}\nDevice of tensor: {some_tensor.device}")

tensor([[0.4498, 0.2620, 0.7493, 0.4155],
        [0.1777, 0.8785, 0.2950, 0.2312],
        [0.3300, 0.9604, 0.3378, 0.7035]])


Dataype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


In [ ]:
some_new_tensor = torch.rand(size=(3, 512, 512), device='cpu', dtype=torch.float16)
some_new_tensor

tensor([[[0.8262, 0.2070, 0.8442,  ..., 0.8354, 0.9019, 0.5093],
         [0.4023, 0.9014, 0.6519,  ..., 0.5415, 0.1938, 0.0728],
         [0.6006, 0.3267, 0.9897,  ..., 0.3682, 0.0586, 0.3491],
         ...,
         [0.3301, 0.7598, 0.9014,  ..., 0.3223, 0.0000, 0.2827],
         [0.5615, 0.9204, 0.6362,  ..., 0.1665, 0.9941, 0.7817],
         [0.9873, 0.6069, 0.2119,  ..., 0.3848, 0.9775, 0.0737]],

        [[0.0615, 0.1860, 0.1777,  ..., 0.4873, 0.4502, 0.5874],
         [0.6753, 0.7832, 0.2661,  ..., 0.2246, 0.9307, 0.1162],
         [0.2388, 0.0649, 0.2275,  ..., 0.7871, 0.6670, 0.9004],
         ...,
         [0.6802, 0.1079, 0.8408,  ..., 0.9766, 0.2471, 0.6074],
         [0.9663, 0.0630, 0.5010,  ..., 0.1836, 0.6006, 0.4292],
         [0.1904, 0.3008, 0.7148,  ..., 0.9282, 0.6016, 0.4238]],

        [[0.3472, 0.7144, 0.9990,  ..., 0.3550, 0.4917, 0.7583],
         [0.8442, 0.5142, 0.9224,  ..., 0.2178, 0.5552, 0.7686],
         [0.5229, 0.3853, 0.9668,  ..., 0.4990, 0.0469, 0.

### Manipulating tensors (Tensor Operations)

Tennsor Operations include
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication


In [ ]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 100

tensor([101, 102, 103])

In [ ]:
tensor * 200

tensor([200, 400, 600])

In [ ]:
tensor / 5

tensor([0.2000, 0.4000, 0.6000])

In [ ]:
tensor - 100

tensor([-99, -98, -97])

In [ ]:
# try out PyTorch in-built functions

torch.mul(tensor, 100)

tensor([100, 200, 300])

In [ ]:
torch.subtract(tensor, 100)

tensor([-99, -98, -97])

In [ ]:
torch.sub(tensor, 100)

tensor([-99, -98, -97])

In [ ]:
torch.add(tensor, 100)

tensor([101, 102, 103])

In [ ]:
torch.div(tensor, 100)

tensor([0.0100, 0.0200, 0.0300])

### Matrix multiplication

Two main ways of performing multiplication in neural networks

1. Element-wise multiplication
2. Matrix multiplication


There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**
* `(2, 3) @ (3, 2)` -> `(2, 2)`
* `(3, 2) @ (2, 3)` -> `(3, 3)`

In [ ]:
#inner dimensions match
torch.matmul(torch.rand(3, 3), torch.rand(3, 2))

tensor([[0.7644, 1.0777],
        [0.6870, 0.9298],
        [0.3184, 0.8336]])

In [ ]:
torch.rand(3, 3) @ torch.rand(3, 2)

tensor([[0.4329, 0.2044],
        [0.9453, 0.7535],
        [0.1709, 0.0602]])

In [ ]:
SOME_MATRIX = torch.randint(high = 10, size=(2, 2))
SOME_MATRIX

tensor([[4, 6],
        [6, 2]])

In [ ]:
torch.matmul(SOME_MATRIX, SOME_MATRIX.mT)

tensor([[52, 36],
        [36, 40]])

In [ ]:
# Element wise multiplication
SOME_MATRIX * SOME_MATRIX

tensor([[16, 36],
        [36,  4]])

In [ ]:
print(f"{SOME_MATRIX} * {SOME_MATRIX}")
print(f"EQUALS: {SOME_MATRIX * SOME_MATRIX}")

tensor([[4, 6],
        [6, 2]]) * tensor([[4, 6],
        [6, 2]])
EQUALS: tensor([[16, 36],
        [36,  4]])


In [ ]:
#MATRIX Multiplication
%%time
torch.matmul(tensor , tensor)

CPU times: user 88 µs, sys: 0 ns, total: 88 µs
Wall time: 93.2 µs


tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
%%time
value = 9
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(23)
CPU times: user 1.75 ms, sys: 0 ns, total: 1.75 ms
Wall time: 3.97 ms


In [ ]:
#MATRIX Multiplication
%%time
torch.matmul(tensor , tensor)

CPU times: user 65 µs, sys: 10 µs, total: 75 µs
Wall time: 78.7 µs


tensor(14)

## One of the most common errors in deep learning: Shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])


print(f"Shape of Tensor A: {tensor_A.size()}\nShape of Tensor B: {tensor_B.size()}")

torch.mm(tensor_A, tensor_B.mT)

Shape of Tensor A: torch.Size([3, 2])
Shape of Tensor B: torch.Size([3, 2])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

A **transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.mT, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
tensor_A.shape

torch.Size([3, 2])

In [ ]:
# The matrix multiplication operation works when the tensor_B is transposed
print(f"Original Shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")

torch.mm(tensor_A, tensor_B.T)

Original Shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum etc (tensor aggregation)



In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10, dtype=torch.float32)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [ ]:
torch.min(x), x.min()

(tensor(0.), tensor(0.))

In [ ]:
x.min(), x.max(), x.mean()

(tensor(0.), tensor(90.), tensor(45.))

In [ ]:
x_2 = torch.arange(0, 100, 10, dtype=torch.int32)

In [ ]:
x_2.type(torch.float32).mean()

tensor(45.)

In [ ]:
x.sum()

tensor(450.)

In [ ]:
x.argmin(), x.argmax()

(tensor(0), tensor(9))

In [ ]:
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of a certain shape, but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), torch.float32)

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#Changing z changes x (because a view of a tensor shares the same memor as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked.shape


torch.Size([4, 9])

In [ ]:
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=-2)
x_stacked.shape, x_stacked

(torch.Size([4, 9]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
x_vstacked = torch.vstack([x, x, x, x])
x_vstacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_hstacked = torch.hstack([x, x, x, x])
x_hstacked.shape, x_hstacked

(torch.Size([36]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
         5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# torch.squeeze()

x = torch.zeros(2, 1, 2, 1, 2)
x.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x)
y.size()


torch.Size([2, 2, 2])

In [ ]:
y = torch.squeeze(x, 0)
y.size()


torch.Size([2, 1, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, 1)
y.size()


torch.Size([2, 2, 1, 2])

In [ ]:
y = torch.squeeze(x, (1, 2, 3))
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_squeezed = x_reshaped.squeeze()

In [ ]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.shape

torch.Size([1, 9])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim(dimension)

print(f"Previous target: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"\nNew shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

New shape: torch.Size([1, 9])


In [ ]:
#torch.permute() - rearranges the dimensions of a target tensor in a specified order

x_original = torch.rand(size=(224, 224, 3)) # height, width, color channels

#Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #Shifts axis 0->1, 1->2 and 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #color channels, height, width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0 , 0] = 23
x_permuted

tensor([[[2.3000e+01, 5.3051e-01, 9.0651e-01,  ..., 9.7015e-01,
          2.4501e-01, 6.7006e-02],
         [1.4406e-01, 1.3790e-01, 5.5263e-01,  ..., 9.6572e-01,
          3.0694e-01, 7.4051e-02],
         [6.9412e-01, 9.6989e-01, 7.2831e-01,  ..., 5.4671e-01,
          2.0946e-01, 9.3756e-01],
         ...,
         [7.1067e-01, 3.8182e-01, 6.3087e-01,  ..., 4.0590e-01,
          9.9034e-01, 3.2598e-01],
         [3.9802e-01, 5.7130e-01, 7.8382e-01,  ..., 9.6566e-01,
          8.9092e-01, 4.5596e-01],
         [2.3527e-01, 7.1245e-01, 6.0845e-01,  ..., 2.7552e-01,
          4.2996e-01, 3.1281e-01]],

        [[1.5561e-01, 6.6755e-01, 5.7918e-01,  ..., 3.6754e-01,
          8.2968e-01, 4.2931e-01],
         [4.8129e-01, 2.9552e-01, 1.2504e-01,  ..., 6.4176e-01,
          3.3324e-01, 7.7419e-01],
         [8.0246e-02, 7.8098e-01, 9.0950e-01,  ..., 7.4332e-01,
          6.9171e-01, 1.6993e-01],
         ...,
         [5.7679e-01, 9.0195e-02, 4.6379e-02,  ..., 2.9100e-01,
          3.249

## indexing (selecting data from tensors with indexing)

Indexing with PyTorch is similiar to indexing with NumPy

In [ ]:
#Create a tensor

import torch

x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x.shape

torch.Size([1, 3, 3])

In [ ]:
#Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Let's index on the most inner bracket (last dimensions)
x[0][1][1]

tensor(5)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
# you can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
#Get all values of the 0th and 1st dimensions but only index 1 of the 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of the 0th and 1st dimension and all values of the 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[:, 2, 2]

tensor([9])

In [ ]:
#Index on x to retunr 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`

* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype unless explicitly specified
array, tensor, tensor.dtype

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]),
 torch.float32)

In [ ]:
array.dtype

dtype('float64')

In [ ]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
#Change value of array, what will this do to 'tensor'?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(8)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
#Change the tensor, what happens to numpy tensor?

tensor = tensor + 10
tensor, numpy_tensor

(tensor([11., 11., 11., 11., 11., 11., 11., 11.]),
 array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

# Reproducibility (trying to take the random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`


To reduce the randomness in neural networks and PyTorch comes the concept of a random seed

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

#Create two random Tensors

random_tensor_A = torch.rand(3, 4)

random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.0793, 0.1280, 0.6731, 0.6464],
        [0.0518, 0.1344, 0.5512, 0.3713],
        [0.9923, 0.0576, 0.8201, 0.4172]])
tensor([[0.7364, 0.6426, 0.3005, 0.7911],
        [0.9225, 0.3313, 0.3191, 0.4486],
        [0.8878, 0.1960, 0.4036, 0.6521]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Lets make some random but reporducible tensors

import torch

RANDOM_SEED = 260758

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.2926, 0.1805, 0.6732, 0.7744],
        [0.5117, 0.7782, 0.2897, 0.8145],
        [0.2533, 0.7128, 0.1448, 0.4291]])
tensor([[0.2926, 0.1805, 0.6732, 0.7744],
        [0.5117, 0.7782, 0.2897, 0.8145],
        [0.2533, 0.7128, 0.1448, 0.4291]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
torch.rand(3, 3)

tensor([[0.3707, 0.1156, 0.0530],
        [0.4253, 0.5677, 0.0174],
        [0.3266, 0.2734, 0.6670]])

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).



### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own CPU - takes a little bit of setup
3. Use cloud computing - GCP, AWS, Azure - these services allow you to use VM's and SaaS services in a pay-as-you-go model

In [ ]:
!nvidia-smi

Sun Oct  1 01:15:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P0    44W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [ ]:
#Check for the GPU access with PyTorch
import torch

torch.cuda.is_available()

True

For PyTorch since its capable of running compute on GPU or CPU, its best practice to setup device agnostic


In [ ]:
#Set up device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"

In [ ]:
device

'cuda'

In [ ]:
#Count the number of GPU's
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPu is because using a GPU results in faster computations/

In [ ]:
# Create a tensor (default on the CPU)

tensor = torch.tensor([1, 2, 3], device="cpu")

print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#move tensor to GPU if available
tensor_on_gpu = tensor.to(device)
print(tensor_on_gpu, tensor_on_gpu.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


### 4. Moving tensors back to the CPU



In [ ]:
# If tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# to fix the GPu tensor with the numpy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

# Exercises and Extra-curriculum


In [ ]:
import torch

torch.manual_seed(0)

In [ ]:
some_random_tensor = torch.rand(size=(7, 7))
some_random_tensor

tensor([[0.1759, 0.2698, 0.1507, 0.0317, 0.2081, 0.9298, 0.7231],
        [0.7423, 0.5263, 0.2437, 0.5846, 0.0332, 0.1387, 0.2422],
        [0.8155, 0.7932, 0.2783, 0.4820, 0.8198, 0.9971, 0.6984],
        [0.5675, 0.8352, 0.2056, 0.5932, 0.1123, 0.1535, 0.2417],
        [0.7262, 0.7011, 0.2038, 0.6511, 0.7745, 0.4369, 0.5191],
        [0.6159, 0.8102, 0.9801, 0.1147, 0.3168, 0.6965, 0.9143],
        [0.9351, 0.9412, 0.5995, 0.0652, 0.5460, 0.1872, 0.0340]])

In [ ]:
another_random_tensor = torch.rand(size=(1,7))
another_random_tensor

tensor([[0.9442, 0.8802, 0.0012, 0.5936, 0.4158, 0.4177, 0.2711]])

In [ ]:
torch.mm(some_random_tensor, another_random_tensor.mT)

tensor([[1.0936],
        [1.6489],
        [2.7013],
        [1.7998],
        [2.3348],
        [2.0344],
        [2.0653]])

In [ ]:
torch.cuda.manual_seed(260758)
random_gpu_tensor = torch.rand(size=(4, 4), device=device)

In [ ]:
random_gpu_tensor, random_gpu_tensor.device

(tensor([[0.8592, 0.5520, 0.1516, 0.8414],
         [0.5533, 0.7040, 0.1535, 0.2869],
         [0.3598, 0.4000, 0.0920, 0.4784],
         [0.3636, 0.7180, 0.3993, 0.7382]], device='cuda:0'),
 device(type='cuda', index=0))